name: PrusaSlicer autobuild trigger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  trigger-autobuild:
    uses: Felix-Rm/prusaslicer-autobuild/.github/workflows/autobuild.yml@main
    with:
      only_if_new_release: true
      create_release_copy: true
      upstream_repo: prusa3d/PrusaSlicer
      upstream_ref: latest:release
      downstream_repo: Felix-Rm/PrusaSlicer
      downstream_feature_branches: 'goo-format-support-dev'
      release_tag_prefix: 'autobuild_'
      release_name_prefix: 'Autobuild for Release of '
      release_body_prefix: |
        This is an autobuild release of PrusaSlicer.
        There are no guarantees that this build is stable, no additional testing has been done.
        &nbsp;
        The PrusaSlicer builds attached below include the following extras:
          - Support for generating .goo files (from goo-format-support-dev branch)
        &nbsp;
        Please note that the attached source archives do not contain the source code of the extras as they are kept seperately on the feature branches listed above.
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}